#!/bin/bash -ex

# Escape spaces in fstab or root will be mounted ro
sed -i 's/\\ /\\040/g' /etc/fstab

echo 'DNSStubListener=no' >> /etc/systemd/resolved.conf
systemctl restart systemd-resolved

dnf install -y dnf-plugins-core iptables-services ipset policycoreutils-python-utils setools-console setroubleshoot-server bind-utils nc git bzip2 tcpdump cronie fail2ban tmux colorized-logs
dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

curl -sfL https://get.k3s.io | sh -

curl -L https://github.com/kubernetes/kompose/releases/download/v1.33.0/kompose-linux-amd64 -o /usr/local/bin/kompose
chmod a+x /usr/local/bin/kompose

cat >> /etc/docker/daemon.json << _EOT_
{
	"log-driver": "json-file",
	"log-opts": {
		"max-size": "10m",
		"max-file": "3"
	}
}
_EOT_


systemctl --now enable iptables.service ip6tables.service
systemctl --now enable fail2ban
systemctl --now enable docker

DPSRV_MNT=/mnt/data

[ -e $DPSRV_MNT ] || mkdir -p $DPSRV_MNT

usermod -a -G docker vagrant
for user in dpsrv ezsso; do
	useradd -G docker -b $DPSRV_MNT -m $user

	[ -d $DPSRV_MNT/$user/.ssh ] || mkdir $DPSRV_MNT/$user/.ssh

	echo "${hcloud_ssh_key_dpsrv}" >> $DPSRV_MNT/$user/.ssh/authorized_keys

	chown -R $user:$user $DPSRV_MNT/$user/.ssh
	chmod -R og-rwx $DPSRV_MNT/$user/.ssh

	[ -d $DPSRV_MNT/$user/.bashrc.d ] || mkdir $DPSRV_MNT/$user/.bashrc.d
	echo ". $DPSRV_MNT/dpsrv/rc/bin/dpsrv.sh" > $DPSRV_MNT/$user/.bashrc.d/dpsrv
	[ $user = dpsrv ] || echo ". $DPSRV_MNT/$user/rc/bin/$user.sh" > $DPSRV_MNT/$user/.bashrc.d/$user
done

cat >> /usr/local/bin/dpsrv-init-projects.sh << _EOT_
#!/bin/bash -ex
user=\$1

pushd $DPSRV_MNT/\$user
git clone https://github.com/maxfortun/git-openssl-secrets.git
pushd git-openssl-secrets
ln -s git-setenv-openssl-secrets-fs.sh git-setenv-openssl-secrets.sh
popd >/dev/null
git clone https://github.com/\$user/rc.git
pushd rc
../git-openssl-secrets/git-init-openssl-secrets.sh
popd >/dev/null
. rc/bin/\$user.sh
\$user-git-clone
\$user-git-init-secrets 

#[ ! -d "$DPSRV_SRV" ] || [ -e srv ] || ln -s $DPSRV_SRV srv

\$user-up

_EOT_

cat >> /usr/local/bin/dpsrv-init.sh << _EOT_
#!/bin/bash -ex
resolved=\$(host "\$(hostname -s).dpsrv.me")

sysctl -w net.ipv4.conf.all.route_localnet=1
#iptables -t nat -A POSTROUTING -m addrtype --src-type LOCAL --dst-type UNICAST -j MASQUERADE -m comment --comment dpsrv:forward:port

while [ -f ~/.config/openssl-salt ]; do
	echo "Waiting for ~/.config"
	sleep 2
done

export HOME=\$\{HOME:-/root}

docker network ls | grep -q '^[^ ]*[ ]*dpsrv' || docker network create dpsrv

for user in dpsrv ezsso; do
	[ ! -e $DPSRV_MNT/\$user/.config ] || continue

	mkdir -p $DPSRV_MNT/\$user
	cp -r /home/host_user/{.config,.gitconfig,.git-credentials} $DPSRV_MNT/\$user/

	chown -R \$user:\$user $DPSRV_MNT/\$user/{.config,.gitconfig,.git-credentials} $DPSRV_MNT/\$user

	sudo -u \$user git config --global credential.helper store
	sudo -u \$user git config --global --add safe.directory /root/dpsrv/rc

	sudo -u \$user /usr/local/bin/dpsrv-init-projects.sh \$user
done

. $DPSRV_MNT/dpsrv/rc/bin/dpsrv.sh
dpsrv-activate-latest

bridgeIP=\$(docker network inspect --format '{{(index .IPAM.Config 0).Gateway}}' dpsrv)
bridgeLabel=\$(ip -json address show to "\$bridgeIP/32"|jq -r '.[].addr_info[].label')
ifconfig \$bridgeLabel promisc

_EOT_

chmod a+x /usr/local/bin/dpsrv-init*.sh

cat >> /usr/lib/systemd/system/dpsrv-init.service << _EOT_
[Unit]
Description=DPSRV init
Requires=multi-user.target
After=multi-user.target

[Service]
Type=simple
ExecStart=/usr/local/bin/dpsrv-init.sh

[Install]
WantedBy=multi-user.target 

_EOT_

cat >> /etc/sudoers.d/dpsrv << _EOT_
dpsrv ALL=(ALL) NOPASSWD:/sbin/iptables,/sbin/ip6tables,/sbin/iptables-save,/sbin/ip6tables-save,/usr/bin/tee /etc/sysconfig/iptables,/usr/bin/tee /etc/sysconfig/ip6tables
_EOT_

cat >> /etc/sudoers.d/ezsso << _EOT_
ezsso ALL=(ALL) NOPASSWD:/sbin/iptables,/sbin/ip6tables,/sbin/iptables-save,/sbin/ip6tables-save,/usr/bin/tee /etc/sysconfig/iptables,/usr/bin/tee /etc/sysconfig/ip6tables
_EOT_

cat >> /etc/yum.repos.d/mongodb.repo << _EOT_
[mongodb]
name=MongoDB
baseurl=https://repo.mongodb.org/yum/redhat/9/mongodb-org/7.0/\$\{basearch}/
gpgkey=https://www.mongodb.org/static/pgp/server-7.0.asc
_EOT_

rpm --import https://www.mongodb.org/static/pgp/server-7.0.asc
dnf install -y mongodb-mongosh-shared-openssl3

systemctl --now enable dpsrv-init


